### ISSUE TITLE
Re-run benchmarks using newer releases

### ISSUE THREAD

**Issue by RSully** [unixpickle/Benchmarks#3]
- Newer release of Swift
- Dart 1.6.0
- PHP 5.6.0

**Comment by RSully** [comment]
Would also be cool to see Go.

**Comment by unixpickle** [comment]
Versions were updated by [f49d39392d3537ebeade1cd9ba64558ed64d7b2a](https://github.com/unixpickle/Benchmarks/commit/f49d39392d3537ebeade1cd9ba64558ed64d7b2a). I am now going to add Go benchmarks.
